package com.example.touhoutd;

public class ImageMapping {
    public static int getImageMapping(String name) {
        switch (name) {
            case "博丽灵梦":
                return R.drawable.bllm;
            case "八云紫":
                return R.drawable.byz;
            case "蕾米莉亚":
                return R.drawable.lmly;
            case "芙兰朵露":
                return R.drawable.fldl;
            case "风见幽香":
                return R.drawable.fjyx;
            case "神绮":
                return R.drawable.sq;
            case "大妖精":
                return R.drawable.dyj;
            case "古明地恋":
                return R.drawable.gmdl;
            case "八坂神奈子":
                return R.drawable.bbsnz;
            case "八意永琳":
                return R.drawable.byyl;
            case "幽幽子":
                return R.drawable.xxsyyz;
            case "洩矢诹访子":
                return R.drawable.xszfz;
            case "雾雨魔理沙":
                return R.drawable.wymls;
            case "封兽鵺":
                return R.drawable.fsy;
            case "帕秋莉":
                return R.drawable.pql;
            case "铃仙":
                return R.drawable.lx;
            case "火焰猫燐":
                return R.drawable.hyml;
            case "十六夜咲夜":
                return R.drawable.slyxy;
            case "东风谷早苗":
                return R.drawable.dfgzm;
            case "灵乌路空":
                return R.drawable.lwlk;
            case "蓬莱山辉夜":
                return R.drawable.plshy;
            case "天子":
                return R.drawable.bnmjtz;
            case "射命丸文":
                return R.drawable.smww;
            case "八云蓝":
                return R.drawable.byl;
            case "村纱水蜜":
                return R.drawable.cssm;
            case "藤原妹红":
                return R.drawable.tymh;
            case "魂魄妖梦":
                return R.drawable.hpym;
            case "纳兹玲":
                return R.drawable.nzl;
            case "秋穰子":
                return R.drawable.qrz;
            case "橙":
                return R.drawable.c;
            case "红美铃":
                return R.drawable.hml;
            case "寅丸星":
                return R.drawable.ywx;
            case "露娜萨":
                return R.drawable.lns;
            case "姬海棠果":
                return R.drawable.jhtg;
            case "莉莉卡":
                return R.drawable.llk;
            case "小恶魔":
                return R.drawable.xem;
            case "琪露诺":
                return R.drawable.qln;
            case "犬走椛":
                return R.drawable.qzh;
            case "莉莉白":
                return R.drawable.llb;
            case "露米娅":
                return R.drawable.lmy;
            case "蕾蒂":
                return R.drawable.ld;
            case "秋静叶":
                return R.drawable.qjy;
            case "米斯蒂娅":
                return R.drawable.msdy;
            case "梅露兰":
                return R.drawable.mll;
            case "古明地觉":
                return R.drawable.gmdj;
            case "永江衣玖":
                return R.drawable.yjyj;
            case "多多良小伞":
                return R.drawable.ddlxs;
            case "圣白莲":
                return R.drawable.sbl;
            case "女仆妖精":
                return R.drawable.npyj;
            case "墓地妖精":
                return R.drawable.mdyj;
            case "上海人偶":
                return R.drawable.shro;
            case "蓬莱人偶":
                return R.drawable.plro;
            case "花田妖精":
                return R.drawable.htyj;
            case "苏我屠自古":
                return R.drawable.swtzg;
            case "物部布都":
                return R.drawable.wbbd;
            case "丰聪耳神子":
                return R.drawable.fcesz;
            case "宫古芳香":
                return R.drawable.ggfx;
            case "霍青娥":
                return R.drawable.hqe;
            default:
                return 0;

        }
    }
}
